
services:
  db:
    image: postgres:17-alpine
    container_name: wallet_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATA_BASE_USER}
      POSTGRES_PASSWORD: ${DATA_BASE_PASSWORD}
      POSTGRES_DB: wallet_db
      TZ: Europe/Moscow
      PG_MAX_CONNECTIONS: 200
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
