spring:
  application:
    name: wallet api
  liquibase:
    enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 100
      minimum-idle: 10
      idle-timeout: 30000
      connection-timeout: 2000
  jpa:
    hibernate:
      ddl-auto: validate

  logging:
    level:
      root: INFO
      org.springframework.cloud: INFO
      org.springframework.web: INFO

server:
  port: 8080