spring:
  application:
    name: wallet api
  liquibase:
    enabled: true

  datasource:
    url: ${DATA_BASE_URL}
    driver-class-name: ${DATA_BASE_DRIVER_CLASS_NAME}
    username: ${DATA_BASE_USER}
    password: ${DATA_BASE_PASSWORD}
    hikari:
      maximum-pool-size: 100
      minimum-idle: 10
      idle-timeout: 30000
      connection-timeout: 2000
  jpa:
    hibernate:
      ddl-auto: validate

  logging:
    level:
      root: INFO
      org.springframework.cloud: INFO
      org.springframework.web: INFO

server:
  port: ${SERVER_PORT}